{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "C_eoViAOhsYk"
      },
      "outputs": [],
      "source": [
        "!pip install streamlit pandas numpy xgboost scikit-learn matplotlib seaborn"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 73
        },
        "id": "aiAI36UmhvIP",
        "outputId": "5ae7da7a-747f-4c7e-acdc-27226264709c"
      },
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-03dfbe38-c62b-4dfc-89b5-b3f022da9aef\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-03dfbe38-c62b-4dfc-89b5-b3f022da9aef\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving Comprehensive_Data_1_025454.csv to Comprehensive_Data_1_025454.csv\n"
          ]
        }
      ],
      "source": [
        "from google.colab import files\n",
        "uploaded = files.upload()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "zJHKPIoah8dB"
      },
      "outputs": [],
      "source": [
        "%%writefile app.py\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import xgboost as xgb\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
        "\n",
        "# ==========================================\n",
        "# 1. PAGE CONFIGURATION & ANIMATED CSS UI\n",
        "# ==========================================\n",
        "st.set_page_config(\n",
        "    page_title=\"UAV Energy Consumption & EDA Dashboard\",\n",
        "    page_icon=\"🛸\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\"\n",
        ")\n",
        "\n",
        "# Custom Animated Background & Styled Components\n",
        "st.markdown(\"\"\"\n",
        "<style>\n",
        "    /* Animated Gradient Background */\n",
        "    .stApp {\n",
        "        background: linear-gradient(-45deg, #0f172a, #1e1b4b, #311042, #0f172a);\n",
        "        background-size: 400% 400%;\n",
        "        animation: gradient 15s ease infinite;\n",
        "        color: #f8fafc;\n",
        "    }\n",
        "\n",
        "    @keyframes gradient {\n",
        "        0% { background-position: 0% 50%; }\n",
        "        50% { background-position: 100% 50%; }\n",
        "        100% { background-position: 0% 50%; }\n",
        "    }\n",
        "\n",
        "    /* Custom Metric Display */\n",
        "    div[data-testid=\"stMetricValue\"] {\n",
        "        font-size: 28px;\n",
        "        color: #38bdf8;\n",
        "    }\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 2. DATA LOADING & MODEL TRAINING (CACHED)\n",
        "# ==========================================\n",
        "@st.cache_data\n",
        "def load_and_train_model():\n",
        "    # Load dataset\n",
        "    df = pd.read_csv('Comprehensive_Data_1_025454.csv')\n",
        "\n",
        "    # Feature Selection & Target Identification\n",
        "    features = [\n",
        "        'Flight_Time_s', 'T_Climb_s', 'T_Hover_s', 'T_Dash_s', 'T_Loiter_s',\n",
        "        'T_Fig8_s', 'T_Land_s', 'Payload_kg', 'Wind_ms', 'Cruise_Alt_m', 'Avg_Speed_ms'\n",
        "    ]\n",
        "    target = 'Battery_Consumed_Pct'\n",
        "\n",
        "    X = df[features]\n",
        "    y = df[target]\n",
        "\n",
        "    # Split and Train Model\n",
        "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
        "\n",
        "    model = xgb.XGBRegressor(\n",
        "        n_estimators=100,\n",
        "        learning_rate=0.1,\n",
        "        max_depth=5,\n",
        "        random_state=42\n",
        "    )\n",
        "    model.fit(X_train, y_train)\n",
        "\n",
        "    # Calculate Evaluation Metrics\n",
        "    y_pred = model.predict(X_test)\n",
        "    metrics = {\n",
        "        'r2': r2_score(y_test, y_pred),\n",
        "        'rmse': np.sqrt(mean_squared_error(y_test, y_pred)),\n",
        "        'mae': mean_absolute_error(y_test, y_pred)\n",
        "    }\n",
        "\n",
        "    return df, model, features, metrics\n",
        "\n",
        "# Load cached data and trained model\n",
        "try:\n",
        "    df, model, feature_names, metrics = load_and_train_model()\n",
        "except FileNotFoundError:\n",
        "    st.error(\"⚠️ Dataset file `Comprehensive_Data_1_025454.csv` not found. Please upload it to your workspace.\")\n",
        "    st.stop()\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 3. NAVIGATION & SIDEBAR INPUT BOXES\n",
        "# ==========================================\n",
        "st.sidebar.title(\"🛸 UAV Control Panel\")\n",
        "app_mode = st.sidebar.radio(\"Navigate\", [\"Energy Prediction\", \"Exploratory Data Analysis (EDA)\"])\n",
        "\n",
        "st.sidebar.markdown(\"---\")\n",
        "st.sidebar.subheader(\"Flight & Mission Inputs\")\n",
        "\n",
        "# Sidebar input boxes (Numeric Text Inputs)\n",
        "user_inputs = {}\n",
        "for col in feature_names:\n",
        "    min_val = float(df[col].min())\n",
        "    max_val = float(df[col].max())\n",
        "    mean_val = float(df[col].mean())\n",
        "\n",
        "    # Determine step size based on float or int\n",
        "    step = 0.1 if isinstance(df[col].iloc[0], (float, np.floating)) else 1.0\n",
        "\n",
        "    user_inputs[col] = st.sidebar.number_input(\n",
        "        label=f\"{col.replace('_', ' ')}\",\n",
        "        min_value=min_val,\n",
        "        max_value=max_val,\n",
        "        value=round(mean_val, 2),\n",
        "        step=step,\n",
        "        help=f\"Valid range: {min_val} to {max_val}\"\n",
        "    )\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 4. VIEW 1: PREDICTION DASHBOARD\n",
        "# ==========================================\n",
        "if app_mode == \"Energy Prediction\":\n",
        "    st.title(\"🔋 Multirotor UAV Battery Consumption Predictor\")\n",
        "    st.markdown(\"Enter flight parameters in the input boxes on the sidebar to estimate battery consumption.\")\n",
        "\n",
        "    col1, col2 = st.columns([1, 1])\n",
        "\n",
        "    with col1:\n",
        "        st.subheader(\"🤖 Model Performance Metrics\")\n",
        "        m_col1, m_col2, m_col3 = st.columns(3)\n",
        "        m_col1.metric(\"R² Accuracy Score\", f\"{metrics['r2'] * 100:.2f}%\")\n",
        "        m_col2.metric(\"RMSE\", f\"{metrics['rmse']:.3f}%\")\n",
        "        m_col3.metric(\"MAE\", f\"{metrics['mae']:.3f}%\")\n",
        "\n",
        "        st.markdown(\"---\")\n",
        "        st.subheader(\"🎯 Run Prediction\")\n",
        "\n",
        "        # Trigger prediction button\n",
        "        if st.button(\"Calculate Battery Consumption\", type=\"primary\", use_container_width=True):\n",
        "            input_df = pd.DataFrame([user_inputs])\n",
        "            prediction = model.predict(input_df)[0]\n",
        "\n",
        "            st.success(\"Calculation Complete!\")\n",
        "\n",
        "            p_col1, p_col2 = st.columns(2)\n",
        "            p_col1.metric(\n",
        "                label=\"Predicted Battery Consumption\",\n",
        "                value=f\"{prediction:.2f}%\"\n",
        "            )\n",
        "            p_col2.metric(\n",
        "                label=\"Estimated Remaining SOC\",\n",
        "                value=f\"{max(0.0, 100.0 - prediction):.2f}%\"\n",
        "            )\n",
        "\n",
        "            # Progress bar visualizer\n",
        "            st.write(\"Battery Consumption Indicator:\")\n",
        "            st.progress(min(max(float(prediction) / 100.0, 0.0), 1.0))\n",
        "\n",
        "    with col2:\n",
        "        st.subheader(\"⚙️ Active Mission Configuration\")\n",
        "        input_summary = pd.DataFrame(list(user_inputs.items()), columns=[\"Parameter\", \"Entered Value\"])\n",
        "        st.dataframe(input_summary, use_container_width=True, height=400)\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 5. VIEW 2: EDA DASHBOARD\n",
        "# ==========================================\n",
        "else:\n",
        "    st.title(\"📊 Exploratory Data Analysis (EDA)\")\n",
        "    st.markdown(\"Explore dataset distributions, feature correlations, and spread across variables.\")\n",
        "\n",
        "    eda_tab1, eda_tab2, eda_tab3 = st.tabs([\"🔥 Correlation Heatmap\", \"📈 Histograms\", \"📦 Boxplots\"])\n",
        "\n",
        "    # Seaborn Style Configuration for Dark Background\n",
        "    plt.style.use('dark_background')\n",
        "\n",
        "    # Tab 1: Correlation Heatmap\n",
        "    with eda_tab1:\n",
        "        st.subheader(\"Feature Correlation Heatmap\")\n",
        "        fig, ax = plt.subplots(figsize=(10, 6))\n",
        "        fig.patch.set_alpha(0.0)\n",
        "        ax.patch.set_alpha(0.0)\n",
        "\n",
        "        corr = df.corr(numeric_only=True)\n",
        "        sns.heatmap(corr, annot=True, fmt=\".2f\", cmap=\"mako\", ax=ax, cbar=True, linewidths=0.5)\n",
        "        st.pyplot(fig)\n",
        "\n",
        "    # Tab 2: Histograms\n",
        "    with eda_tab2:\n",
        "        st.subheader(\"Feature Distribution Histograms\")\n",
        "        selected_hist_col = st.selectbox(\"Select Feature for Histogram\", df.columns, index=0)\n",
        "\n",
        "        fig, ax = plt.subplots(figsize=(8, 4))\n",
        "        fig.patch.set_alpha(0.0)\n",
        "        ax.patch.set_alpha(0.0)\n",
        "\n",
        "        sns.histplot(df[selected_hist_col], kde=True, color=\"#38bdf8\", bins=30, ax=ax)\n",
        "        ax.set_title(f\"Distribution of {selected_hist_col}\", color=\"white\")\n",
        "        st.pyplot(fig)\n",
        "\n",
        "    # Tab 3: Boxplots\n",
        "    with eda_tab3:\n",
        "        st.subheader(\"Feature Outlier Analysis (Boxplots)\")\n",
        "        selected_box_col = st.selectbox(\"Select Feature for Boxplot\", df.columns, index=7)\n",
        "\n",
        "        fig, ax = plt.subplots(figsize=(8, 3))\n",
        "        fig.patch.set_alpha(0.0)\n",
        "        ax.patch.set_alpha(0.0)\n",
        "\n",
        "        sns.boxplot(x=df[selected_box_col], color=\"#a855f7\", ax=ax)\n",
        "        ax.set_title(f\"Boxplot of {selected_box_col}\", color=\"white\")\n",
        "        st.pyplot(fig)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "qE-Hu6V6ERFL"
      },
      "outputs": [],
      "source": [
        "# 1. Download and set up Cloudflare Tunnel\n",
        "!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb\n",
        "!dpkg -i cloudflared-linux-amd64.deb > /dev.null\n",
        "\n",
        "# 2. Run Streamlit and expose it via Cloudflare\n",
        "!streamlit run app.py & cloudflared tunnel --url http://localhost:8501"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "background_save": true,
          "base_uri": "https://localhost:8080/"
        },
        "id": "VV19S6a2iKLe",
        "outputId": "e7bf478a-986e-4ef8-c53e-e6900a3364bc"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "35.194.255.126\n",
            "/bin/bash: line 1: streamlit: command not found\n",
            "\u001b[1G\u001b[0K⠙\u001b[1G\u001b[0K⠹\u001b[1G\u001b[0K⠸\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K⠴\u001b[1G\u001b[0K⠦\u001b[1G\u001b[0K\u001b[1G\u001b[0JNeed to install the following packages:\n",
            "localtunnel@2.0.2\n",
            "Ok to proceed? (y) \u001b[20G"
          ]
        }
      ],
      "source": [
        "# Get your Colab instance external IP address (Password for localtunnel)\n",
        "!curl ipv4.icanhazip.com\n",
        "\n",
        "# Start Streamlit app in background and expose via localtunnel on port 8501\n",
        "!streamlit run app.py & npx localtunnel --port 8501"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "LYXD40lmzar7"
      },
      "outputs": [],
      "source": [
        "!curl ipv4.icanhazip.com"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
